# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21efd86aeee399bac8f926fadb231f7e89528ba278720d91ee92bc7982284463d6e8be6c855f909f91e8a2489a127bdadde2cc765c6af868d2b783f6021fd80a

test:
  secret_key_base: 6b1b3e154f2409b8817f164c8b0219350f25fb49c93065b1b3bfdcc413a85c16df06fd84839926078cdf253eb809e808a6cdd4187f5470b9d00dfa7717a7c94f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
